import React, { createContext, useContext, useMemo, useState } from "react";

type Language = "en" | "mn";

interface LanguageContextValue {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string, vars?: Record<string, string | number>) => string;
}

const STORAGE_KEY = "seo-audit-lang-v1";

const translations: Record<Language, Record<string, string>> = {
  en: {
    "lang.label": "Language",
    "lang.en": "English",
    "lang.mn": "Mongolian",
    "home.title": "SEO Audit Tracker",
    "home.report": "SEO Audit Report",
    "home.heading": "Comprehensive SEO Audit",
    "home.progress": "Progress",
    "home.tasks": "tasks",
    "home.highPriority": "High Priority",
    "home.remaining": "remaining",
    "home.overallScore": "Overall Score",
    "home.complete": "complete",
    "home.redFlagged": "Red-Flagged High Priority Items",
    "home.noRedFlags": "No high-priority red flags found in the latest retest.",
    "home.auditorNote": "Auditor's Note",
    "home.noteBody": "Click the circle icon on any task to cycle through statuses: To Do -> In Progress -> Done. Expand any task with \"How to fix\" for detailed action steps. Your progress is automatically saved in your browser.",
    "home.dataHandling": "Data handling: progress is stored locally in the browser, but retest, URL inspection, and email actions send user-triggered requests to backend functions.",
    "home.readPolicy": "Read privacy, security, and cookie details",
    "home.localSave": "Progress is saved locally in your browser. Some audit actions call backend functions only when you trigger them.",
    "home.policyInfo": "Privacy, security, and cookie information",
    "home.auditFor": "SEO Audit for {site} · Audited {date} · Generated by {auditor}",
    "home.goTop": "Go to top",
    "sidebar.brand": "SEO Audit",
    "sidebar.go": "Go",
    "sidebar.crawling": "Crawling site...",
    "sidebar.done": "Done",
    "sidebar.tasksComplete": "{done} of {total} tasks complete",
    "sidebar.auditComplete": "Audit Complete!",
    "sidebar.categories": "Categories",
    "sidebar.auditDate": "Audit Date",
    "sidebar.niche": "Niche",
    "sidebar.automation": "Automation",
    "sidebar.autoRetest": "Auto retest",
    "sidebar.off": "Off",
    "sidebar.daily": "Daily",
    "sidebar.weekly": "Weekly",
    "sidebar.runsOpen": "Runs while this dashboard is open.",
    "sidebar.retestTrend": "Last 7 retests trend",
    "sidebar.doneItems": "done items",
    "sidebar.emailReport": "Email Report",
    "sidebar.sending": "Sending",
    "sidebar.send": "Send",
    "sidebar.emailHint": "Request an emailed copy and save your contact.",
    "sidebar.retesting": "Retesting...",
    "sidebar.retestNow": "Retest now",
    "sidebar.lastRetest": "Last retest",
    "sidebar.downloadJson": "Download JSON",
    "sidebar.downloadMd": "Download MD",
    "sidebar.resetAll": "Reset all progress",
    "sidebar.resetConfirm": "Reset all progress? This cannot be undone.",
  },
  mn: {
    "lang.label": "Хэл",
    "lang.en": "Англи",
    "lang.mn": "Монгол",
    "home.title": "SEO Аудит Хянагч",
    "home.report": "SEO Аудит Тайлан",
    "home.heading": "Дэлгэрэнгүй SEO Аудит",
    "home.progress": "Явц",
    "home.tasks": "даалгавар",
    "home.highPriority": "Өндөр Эрэмбэ",
    "home.remaining": "үлдсэн",
    "home.overallScore": "Нийт Үнэлгээ",
    "home.complete": "дууссан",
    "home.redFlagged": "Улаан Тэмдэгтэй Өндөр Эрэмбийн Асуудлууд",
    "home.noRedFlags": "Сүүлийн дахин шалгалтаар өндөр эрэмбийн улаан тэмдэгтэй асуудал илрээгүй.",
    "home.auditorNote": "Аудиторын Тэмдэглэл",
    "home.noteBody": "Даалгаврын тойрог дүрс дээр дарж төлөвөө солино: Хийгдээгүй -> Хийгдэж байна -> Дууссан. \"How to fix\" хэсгийг нээгээд дэлгэрэнгүй алхмуудыг харна уу. Явц таны браузерт автоматаар хадгалагдана.",
    "home.dataHandling": "Өгөгдөл: явц браузерт дотоодоор хадгалагдана. Харин дахин шалгах, URL шалгах, имэйл илгээх үйлдлүүд хэрэглэгчийн дарсан үед backend функц рүү хүсэлт явуулна.",
    "home.readPolicy": "Нууцлал, аюулгүй байдал, cookie мэдээлэл",
    "home.localSave": "Явц таны браузерт локал хадгалагдана. Зарим аудит үйлдэл зөвхөн таны дарсан үед backend функц дуудагдана.",
    "home.policyInfo": "Нууцлал, аюулгүй байдал, cookie мэдээлэл",
    "home.auditFor": "{site} сайтын SEO аудит · Шалгасан огноо: {date} · Үүсгэсэн: {auditor}",
    "home.goTop": "Дээш очих",
    "sidebar.brand": "SEO Аудит",
    "sidebar.go": "Шалгах",
    "sidebar.crawling": "Сайт шалгаж байна...",
    "sidebar.done": "Дууссан",
    "sidebar.tasksComplete": "{total}-с {done} даалгавар дууссан",
    "sidebar.auditComplete": "Аудит Дууслаа!",
    "sidebar.categories": "Ангиллууд",
    "sidebar.auditDate": "Аудит Огноо",
    "sidebar.niche": "Салбар",
    "sidebar.automation": "Автоматжуулалт",
    "sidebar.autoRetest": "Автоматаар дахин шалгах",
    "sidebar.off": "Унтраалттай",
    "sidebar.daily": "Өдөр бүр",
    "sidebar.weekly": "Долоо хоног бүр",
    "sidebar.runsOpen": "Энэ самбар нээлттэй үед ажиллана.",
    "sidebar.retestTrend": "Сүүлийн 7 дахин шалгалтын чиг хандлага",
    "sidebar.doneItems": "дууссан зүйл",
    "sidebar.emailReport": "Имэйл Тайлан",
    "sidebar.sending": "Илгээж байна",
    "sidebar.send": "Илгээх",
    "sidebar.emailHint": "Тайланг имэйлээр илгээх хүсэлт илгээнэ.",
    "sidebar.retesting": "Дахин шалгаж байна...",
    "sidebar.retestNow": "Одоо дахин шалгах",
    "sidebar.lastRetest": "Сүүлд шалгасан",
    "sidebar.downloadJson": "JSON татах",
    "sidebar.downloadMd": "MD татах",
    "sidebar.resetAll": "Бүх явцыг дахин тохируулах",
    "sidebar.resetConfirm": "Бүх явцыг тэглэх үү? Буцаах боломжгүй.",
  },
};

const LanguageContext = createContext<LanguageContextValue | null>(null);

function loadLanguage(): Language {
  // Language toggle removed: keep UI in English.
  return "en";
}

function interpolate(text: string, vars?: Record<string, string | number>): string {
  if (!vars) return text;
  return text.replace(/\{(\w+)\}/g, (_, token: string) => String(vars[token] ?? `{${token}}`));
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>(loadLanguage);

  const setLanguage = (next: Language) => {
    setLanguageState(next);
    try {
      localStorage.setItem(STORAGE_KEY, next);
    } catch {}
  };

  const t = useMemo(
    () =>
      (key: string, vars?: Record<string, string | number>) => {
        const source = translations[language][key] ?? translations.en[key] ?? key;
        return interpolate(source, vars);
      },
    [language]
  );

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}
